name: changesets (master)

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    environment:
      name: npm

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      published-packages: ${{ steps.changesets.outputs.publishedPackages }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn

      - name: Configure git
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @neo4j:registry https://registry.npmjs.org
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release PR or release
        id: changesets
        uses: changesets/action@e9cc34b540dd3ad1b030c57fd97269e8f6ad905a # v1.4.1
        with:
          title: changesets for branch `master`
          version: yarn changeset-version-master
          publish: yarn release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Create release branch for merging into dev
        if: steps.changesets.outputs.published == 'true'
        uses: peterjgrainger/action-create-branch@08259812c8ebdbf1973747f9297e332fa078d3c1 # v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
        with:
          branch: "release/${{ github.sha }}"

      - name: pull-request
        if: steps.changesets.outputs.published == 'true'
        uses: repo-sync/pull-request@65785d95a5a466e46a9d0708933a3bd51bbf9dde # renovate: tag=v2.6.2
        with:
          source_branch: "release/${{ github.sha }}"
          destination_branch: "dev"
          pr_title: "Merge ${{ github.ref }} into dev"
          github_token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}

  slack-notify:
    needs:
      - release

    if: ${{ needs.release.outputs.published == 'true' }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.published-packages) }}

    steps:
      - name: Send Slack announcement of release
        if: matrix.package.name == '@neo4j/graphql'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: '{"version":"${{ matrix.package.version }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_ANNOUNCEMENT_WEBHOOK_URL }}
