name: "CLA Check"

on:
  pull_request_target:
    branches:
      - dev

jobs:
  cla-check:
    if: github.event.pull_request.user.login != 'renovate[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: neo-technology/whitelist-check
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: |
          owner=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          repository=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)

          ./bin/examine-pull-request "$owner" "$repository" "${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}" "$PULL_REQUEST_NUMBER" cla-database.csv
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
