name: "dev"

concurrency: "dev"

on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  code-scanning:
    uses: ./.github/workflows/reusable-codeql-analysis.yml

  unit-tests:
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}

  api-library-tests:
    uses: ./.github/workflows/reusable-api-library-tests.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}

  package-tests:
    uses: ./.github/workflows/reusable-package-tests.yml

  integration-tests-on-prem:
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}

  integration-tests-on-prem-nightly:
    uses: ./.github/workflows/reusable-integration-tests-on-prem-nightly.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_NEO4J_DEV_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_NEO4J_DEV_SECRET_ACCESS_KEY }}

  notification:
    runs-on: ubuntu-latest

    needs:
      - code-scanning
      - unit-tests
      - api-library-tests
      - package-tests
      - integration-tests-on-prem
      - integration-tests-on-prem-nightly

    if: always()

    steps:
      - uses: martialonline/workflow-status@fe13c6a4716673e224038aa1b02387352fb35e13 # v4
        id: check
      - name: Send Slack announcement of pipeline failure
        if: steps.check.outputs.status == 'failure' && github.event_name == 'schedule'
        uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
        with:
          payload: '{"url":"https://github.com/neo4j/graphql/actions/runs/${{ github.run_id }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PIPELINE_FAILURE_WEBHOOK_URL }}
