name: "dev"

concurrency: "dev"

on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  # Let's consider the value of testing examples
  # Perhaps we need some newer, better examples for testing
  neo-push-tests:
    uses: ./.github/workflows/reusable-neo-push-tests.yml

  unit-tests:
    uses: ./.github/workflows/reusable-unit-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  api-library-tests:
    uses: ./.github/workflows/reusable-api-library-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # nextjs-app-setup:
  #   uses: ./.github/workflows/reusable-nextjs-app-setup.yml

  package-tests:
    uses: ./.github/workflows/reusable-package-tests.yml

  integration-tests-on-prem:
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-tests-on-prem-nightly:
    uses: ./.github/workflows/reusable-integration-tests-on-prem-nightly.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_NEO4J_DEV_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_NEO4J_DEV_SECRET_ACCESS_KEY }}

  toolbox-tests:
    uses: ./.github/workflows/reusable-toolbox-tests.yml

  cypher-builder-tests:
    uses: ./.github/workflows/reusable-cypher-builder-tests.yml

  aura-free-tests:
    uses: ./.github/workflows/reusable-aura-tests.yml
    secrets:
      URI: ${{ secrets.AURA_FREE_URI }}
      PASSWORD: ${{ secrets.AURA_FREE_PASSWORD }}
    concurrency: aura-free

  aura-professional-tests:
    uses: ./.github/workflows/reusable-aura-tests.yml
    secrets:
      URI: ${{ secrets.AURA_PROFESSIONAL_URI }}
      PASSWORD: ${{ secrets.AURA_PROFESSIONAL_PASSWORD }}
    concurrency: aura-professional

  aura-5-tests:
    uses: ./.github/workflows/reusable-aura-tests.yml
    secrets:
      URI: ${{ secrets.AURA_5_URI }}
      PASSWORD: ${{ secrets.AURA_5_PASSWORD }}
    concurrency: aura-5
