name: Project card moved

on:
  project_card:
    types:
      - moved

jobs:
  add_confirmed_label:
    if: github.event.project_card.column_id == '17295560'

    runs-on: ubuntu-latest

    steps:
      - name: add labels
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # renovate: tag=v1.0.4
        with:
          add-labels: "confirmed"
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
  add_high_priority_label:
    if: github.event.project_card.column_id == '17286751'

    runs-on: ubuntu-latest

    steps:
      - name: add labels
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # renovate: tag=v1.0.4
        with:
          add-labels: "high priority"
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
