name: "@neo4j/graphql-amqp-subscriptions-engine E2E tests"

on:
  workflow_call:

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        graphql-version:
          - "^15.0.0"
          - "^16.0.0"
        neo4j-version:
          #   - 4.4-community
          - 4.4-enterprise
          #   - 5-community
          - 5-enterprise
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/mypassword
          NEO4J_PLUGINS: '["apoc"]'
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        ports:
          - 7687:7687
      rabbitmq:
        image: rabbitmq@sha256:c25d14830ba808c7ae0e6c7bae0148362c6cd3b719da09fa307ce228f0b3248e
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Overwrite GraphQL version
        run: yarn up --exact graphql@${{ matrix.graphql-version }}
      - name: Run packages/graphql-amqp-subscriptions-engine e2e tests
        run: yarn run test:e2e --coverage
        working-directory: packages/graphql-amqp-subscriptions-engine
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: mypassword
          NEO_URL: bolt://localhost:7687
          RABBITMQ_HOST: localhost
          RABBITMQ_USER: guest
          RABBITMQ_PASSWORD: guest
      - name: Archive coverage report
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine-${{ matrix.graphql-version }}-${{ matrix.neo4j-version }}
          path: packages/graphql-amqp-subscriptions-engine/coverage/

  merge-e2e-tests-results:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine
          pattern: e2e-coverage-graphql-amqp-subscriptions-engine-*
