name: "@neo4j/graphql-amqp-subscriptions-engine E2E tests"

on:
  workflow_call:

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        graphql-version:
          - "^15.0.0"
          - "^16.0.0"
        neo4j-version:
          #   - 4.4-community
          - 4.4-enterprise
          #   - 5-community
          - 5-enterprise
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/mypassword
          NEO4J_PLUGINS: '["apoc"]'
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        ports:
          - 7687:7687
      rabbitmq:
        image: rabbitmq@sha256:29d08b0b96a51ec9f4c2ce76e636538dfb5e09a5ee62369d3f9ba9ce8b77f285
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Overwrite GraphQL version
        run: yarn up --exact graphql@${{ matrix.graphql-version }}
      - name: Run packages/graphql-amqp-subscriptions-engine e2e tests
        run: yarn run test:e2e --coverage
        working-directory: packages/graphql-amqp-subscriptions-engine
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: mypassword
          NEO_URL: bolt://localhost:7687
          RABBITMQ_HOST: localhost
          RABBITMQ_USER: guest
          RABBITMQ_PASSWORD: guest
      - name: Archive coverage report
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine-${{ matrix.graphql-version }}-${{ matrix.neo4j-version }}
          path: packages/graphql-amqp-subscriptions-engine/coverage/

  merge-e2e-tests-results:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine
          pattern: e2e-coverage-graphql-amqp-subscriptions-engine-*
