name: "@neo4j/graphql-amqp-subscriptions-engine E2E tests"

on:
  workflow_call:

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        graphql-version:
          - "^15.0.0"
          - "^16.0.0"
        neo4j-version:
          #   - 4.4-community
          - 4.4-enterprise
          #   - 5-community
          - 5-enterprise
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/mypassword
          NEO4J_PLUGINS: '["apoc"]'
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        ports:
          - 7687:7687
      rabbitmq:
        image: rabbitmq@sha256:a5faa74a3bef6c5e589d8971ff55d4c825860b92fbc48eeb0141d2535f150e7a
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Overwrite GraphQL version
        run: yarn up --exact graphql@${{ matrix.graphql-version }}
      - name: Run packages/graphql-amqp-subscriptions-engine e2e tests
        run: yarn run test:e2e --coverage
        working-directory: packages/graphql-amqp-subscriptions-engine
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: mypassword
          NEO_URL: bolt://localhost:7687
          RABBITMQ_HOST: localhost
          RABBITMQ_USER: guest
          RABBITMQ_PASSWORD: guest
      - name: Archive coverage report
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine-${{ matrix.graphql-version }}-${{ matrix.neo4j-version }}
          path: packages/graphql-amqp-subscriptions-engine/coverage/

  merge-e2e-tests-results:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine
          pattern: e2e-coverage-graphql-amqp-subscriptions-engine-*
