name: "Toolbox Build"

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "packages/graphql/src/**"
      - "packages/graphql-toolbox/**"

jobs:
  build-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      # the introspector is a referenced project by the Toolbox.
      - name: Build the introspector
        run: yarn build
        working-directory: packages/introspector
      - name: Build the Toolbox
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          yarn build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber
        working-directory: packages/graphql-toolbox
      - name: Archive Toolbox build
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: graphqltoolbox
          path: packages/graphql-toolbox/dist
