name: "Toolbox Teardown"

on:
  pull_request_target:
    paths:
      - "packages/graphql/src/**"
      - "packages/graphql-toolbox/**"
    types:
      - closed

jobs:
  teardown-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Teardown graphql-toolbox
        run: |
          npm install -g surge
          surge teardown neo4j-graphql-toolbox-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd # v2.8.0
        with:
          header: toolbox
          message: |
            Thanks for the Neo4j GraphQL Toolbox updates.

            The Neo4j GraphQL Toolbox has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
