name: "UI Publish"

on:
  workflow_run:
    workflows: ["UI Build"]
    types:
      - completed

jobs:
  publish-ui:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: "Download built UI"
        uses: actions/github-script@v6.3.3
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "graphqlui"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/graphqlui.zip', Buffer.from(download.data));
      - run: unzip graphqlui.zip
      - id: get-pr-number
        run: |
          number=$(<prnumber)
          case "$number" in ''|*[!0-9]*) echo "Provided PR number is not an integer"; exit 1 ;; esac
          echo "pr-number=$number" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Publish UI
        run: |
          npm install -g surge
          surge . neo4j-graphql-toolbox-stage-${{ steps.get-pr-number.outputs.pr-number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56 # tag=v2.3.0
        with:
          number: ${{ steps.get-pr-number.outputs.pr-number }}
          message: |
            Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

            Check out your changes at https://neo4j-graphql-toolbox-stage-${{ steps.get-pr-number.outputs.pr-number }}.surge.sh

            Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
