name: "UI Build"

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "packages/graphql/src/**"
      - "packages/graphql-toolbox/**"

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      # the introspector is a referenced project by the Toolbox.
      - name: Build the introspector
        run: yarn build
        working-directory: packages/introspector
      - name: UI build
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          yarn
          yarn build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber
        working-directory: packages/graphql-toolbox
      - name: Archive UI
        uses: actions/upload-artifact@v3
        with:
          name: graphqlui
          path: packages/graphql-toolbox/dist
