name: "yarn update"

on:
  workflow_dispatch:
  schedule:
    - cron: "5 3 1 * *"

jobs:
  yarn-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: yarn install
        run: yarn
      - name: update yarn
        run: yarn set version stable
      - name: yarn install (new version)
        run: yarn
      - name: update typescript plugin
        run: yarn plugin import typescript
      - name: update version plugin
        run: yarn plugin import version
      - name: update workspace-tools plugin
        run: yarn plugin import workspace-tools
      - name: yarn install (new plugin versions)
        run: yarn
      - name: Set output variables
        id: vars
        run: |
          today="$(date +%Y-%m-%d)"
          echo "title=[YARN UPDATE] Update yarn $today" >> "$GITHUB_OUTPUT"
          echo "branch=yarn-update-$today" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@d7db273d6c7206ba99224e659c982ae34a1025e3 # v4.2.1
        with:
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          commit-message: ${{ steps.vars.outputs.title }}
          title: ${{ steps.vars.outputs.title }}
          branch: ${{ steps.vars.outputs.branch }}
